mailproject1/mailproject1/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('paipeline/', include('paipeline.urls')),
    path('admin/', admin.site.urls),
]

mailproject1/paipeline/urls.py
from django.urls import path
from . import views
app_name = "paipeline"

urlpatterns = [
    path('', views.index, name='index')
]

mailproject1/paipeline/models.py
from django.db import models

# Create your models here.

mailproject1/paipeline/views.py
from django.shortcuts import render
from django.http import HttpResponse
import dill

ifile = open("./savedModels/knn_model.dill", "rb")
model = dill.load(ifile)
ifile.close()
files_names = ['KNeighborsClassifier_v1.dill','MultinomialNB_v1.dill','RandomForestClassifier_v1.dill','SVC_v1.dill']
models = list()
for file in files_names:
    ifile = open(f'./savedModels/{file}', "rb")
    model = dill.load(ifile)
    models.append(model)
    ifile.close()


def index(request):
    mail = request.POST.get('mail', "")
    result = ""
    if(mail):
        result = model.msg_predict(mail)[0]
    return render(request, 'Index.html', {'result': result, 'mail': mail})

mailproject1/paipeline/templates/about.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>NewsGrid || About</title>
    <link href="https://fonts.googleapis.com/css2?family=Lato&family=Staatliches&display=swap" rel="stylesheet">
    <script src="https://kit.fontawesome.com/dab59ba1f7.js" crossorigin="anonymous"></script>
    <link rel="shortcut icon" type="image/x-icon" href="/favicon.ico">

    <link rel="stylesheet" href="Css/style.css">
    <link rel="stylesheet" href="Css/mobile.css">
</head>
<body>
    <nav class="navBar">
        <div class="container">
            <img src="Images/logo.png" alt="GridNews">
            <div class="social">
                <a href="http://facebook.com" target="_blank"><i class="fab fa-facebook fa-2x"></i></a>
                <a href="http://twitter.com" target="_blank"><i class="fab fa-twitter fa-2x"></i></a>
                <a href="http://instagram.com" target="_blank"><i class="fab fa-instagram fa-2x"></i></a>
                <a href="http://youtube.com" target="_blank"><i class="fab fa-youtube fa-2x"></i></a>
            </div>
            <div class="navBtns">
                <a href="index.html" class="btn nCurrent">Home</a>
                <a href="about.html" class="btn current">About</a>
            </div>
        </div>
    </nav>
 
    <section class="about">
        <div class="container">
            <div class="aboutContent card bg-light">
                <h1 class="l-header">About Our Organization</h1>
                <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Labore debitis beatae ad doloremque voluptate, blanditiis suscipit error quam fugit sapiente, aliquid quia libero incidunt recusandae enim voluptas nulla sequi similique? Temporibus ad est minima magni molestias obcaecati consequatur cumque exercitationem deleniti eos, animi facere recusandae, pariatur eveniet neque? Voluptatem, molestias.</p>
                <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Beatae dignissimos dolorum ipsam corporis similique! Quis, esse minus? Ducimus tempore provident sunt officia? Velit temporibus harum voluptate, ipsum quisquam rerum doloremque consectetur quos incidunt deleniti dicta excepturi ratione, fugiat ad fuga in nam dolorum aut minus esse voluptatum suscipit et quae. Repellendus minus, ratione aperiam commodi voluptas iusto aliquam sapiente. Aut obcaecati, corporis praesentium porro nostrum excepturi animi repellendus incidunt non quis nisi assumenda voluptas possimus molestiae laboriosam iure sed architecto in perferendis magnam blanditiis voluptatum placeat labore odio? Unde id dolore aliquam, quas sit harum, saepe maiores facilis aliquid molestiae qui. Praesentium rerum, minima fugit laudantium quaerat voluptatem pariatur sequi saepe blanditiis nobis natus possimus quo, assumenda numquam sit, eaque accusamus incidunt exercitationem quis deleniti quisquam corrupti vel? Ut quisquam consequatur, doloribus voluptatibus iusto quaerat, sint non magnam reiciendis amet quos sapiente excepturi omnis laboriosam nobis, expedita delectus odio provident?</p>
            </div>

            <aside class="join card bg-pr">
                <h2>Join our club</h2>
                <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Odit, id?</p>
                <a href="#" class="btn bg-dark">Join Now</a>
            </aside>
        </div>
    </section>

    <footer class="mainFooter bg-dark py-p2">
        <div class="container">

            <div class="card">
                <img src="Images/logo_light.png" alt="">
                <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Velit deserunt assumenda enim non? Ratione ipsum voluptates fuga eos earum vitae.</p>
            </div>

            <div class="card">
                <h3>Email Newsletter</h3>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit.</p>

                <form name="contact" method="POST" data-netlify="true">
                    <input type="email" name="email" placeholder="Enter Email...">
                    <input type="submit" value="Submit" class="btn pr-btn">
                </form>
            </div>

            <div class="card">
                <h3>Site Links</h3>
                <ul>
                    <li><a href="#">Help & Support</a></li>
                    <li><a href="#">Privacy Policy</a></li>
                    <li><a href="#">About Us</a></li>
                    <li><a href="#">Contact</a></li>
                </ul>
            </div>

            <div class="card">
                <h2>Join Our Club</h2>
                    <p> Lorem ipsum dolor sit amet consectetur adipisicing elit. Modi, nesciunt!</p>
                    <a href="#" class="btn sc-btn">Join Now</a>
            </div>

            <div class="footer">
                <p>Copyright &copy; 2019, All Rights Reserved</p>
            </div>
        </div>
    </footer>
</body>
</html>

mailproject1/paipeline/templates/article.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>NewsGrid || Article's Name</title>
    <link href="https://fonts.googleapis.com/css2?family=Lato&family=Staatliches&display=swap" rel="stylesheet">
    <script src="https://kit.fontawesome.com/dab59ba1f7.js" crossorigin="anonymous"></script>
    <link rel="shortcut icon" type="image/x-icon" href="/favicon.ico">

    <link rel="stylesheet" href="Css/style.css">
    <link rel="stylesheet" href="Css/mobile.css">
</head>

<body>
    <nav class="navBar">
        <div class="container">
            <img src="Images/logo.png" alt="GridNews">
            <div class="social">
                <a href="http://facebook.com" target="_blank"><i class="fab fa-facebook fa-2x"></i></a>
                <a href="http://twitter.com" target="_blank"><i class="fab fa-twitter fa-2x"></i></a>
                <a href="http://instagram.com" target="_blank"><i class="fab fa-instagram fa-2x"></i></a>
                <a href="http://youtube.com" target="_blank"><i class="fab fa-youtube fa-2x"></i></a>
            </div>
            <div class="navBtns">
                <a href="index.html" class="btn nCurrent">Home</a>
                <a href="about.html" class="btn current">About</a>
            </div>
        </div>
    </nav>

    <section class="article">
        <div class="container">
            <div class="articleContent card bg-light">
                <img src="Images/articles/ent1.jpg" alt="">
                <h1 class="l-header">About Our Organization</h1>
                <div class="meta">
                    <small>
                        <p> <i class="fas fa-user"></i> Written By John Doe January 12, 2019</p>
                    </small>
                    <div class="category ent">ENTERTAINMENT</div>
                </div>
                <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Labore debitis beatae ad doloremque
                    voluptate, blanditiis suscipit error quam fugit sapiente, aliquid quia libero incidunt recusandae
                    enim voluptas nulla sequi similique? Temporibus ad est minima magni molestias obcaecati consequatur
                    cumque exercitationem deleniti eos, animi facere recusandae, pariatur eveniet neque? Voluptatem,
                    molestias.</p>
                <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Beatae dignissimos dolorum ipsam corporis
                    similique! Quis, esse minus? Ducimus tempore provident sunt officia? Velit temporibus harum
                    voluptate, ipsum quisquam rerum doloremque consectetur quos incidunt deleniti dicta excepturi
                    ratione, fugiat ad fuga in nam dolorum aut minus esse voluptatum suscipit et quae. Repellendus
                    minus, ratione aperiam commodi voluptas iusto aliquam sapiente. Aut obcaecati, corporis praesentium
                    porro nostrum excepturi animi repellendus incidunt non quis nisi assumenda voluptas possimus
                    molestiae laboriosam iure sed architecto in perferendis magnam blanditiis voluptatum placeat labore
                    odio? Unde id dolore aliquam, quas sit harum, saepe maiores facilis aliquid molestiae qui.
                    Praesentium rerum, minima fugit laudantium quaerat voluptatem pariatur sequi saepe blanditiis nobis
                    natus possimus quo, assumenda numquam sit, eaque accusamus incidunt exercitationem quis deleniti
                    quisquam corrupti vel? Ut quisquam consequatur, doloribus voluptatibus iusto quaerat, sint non
                    magnam reiciendis amet quos sapiente excepturi omnis laboriosam nobis, expedita delectus odio
                    provident?</p>
            </div>

            <aside class="categoriesAside card bg-light">
                <h2>Categories</h2>
                <ul>
                    <li><a href="#"><i class="fas fa-chevron-right"></i> Sport</a></li>
                    <li><a href="#"><i class="fas fa-chevron-right"></i> Entertainment</a></li>
                    <li><a href="#"><i class="fas fa-chevron-right"></i> Technology</a></li>
                    <li><a href="#"><i class="fas fa-chevron-right"></i> Fashion</a></li>
                    <li><a href="#"><i class="fas fa-chevron-right"></i> Shopping</a></li>
                </ul>
            </aside>
            <aside class="join card bg-sc">
                <h2>Join our club</h2>
                <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Odit, id?</p>
                <a href="#" class="btn bg-dark">Join Now</a>
            </aside>
        </div>
    </section>

    <footer class="mainFooter bg-dark py-p2">
        <div class="container">

            <div class="card">
                <img src="Images/logo_light.png" alt="">
                <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Velit deserunt assumenda enim non? Ratione
                    ipsum voluptates fuga eos earum vitae.</p>
            </div>

            <div class="card">
                <h3>Email Newsletter</h3>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit.</p>

                <form name="contact" method="POST" data-netlify="true">
                    <input type="email" name="email" placeholder="Enter Email...">
                    <input type="submit" value="Submit" class="btn pr-btn">
                </form>
            </div>

            <div class="card">
                <h3>Site Links</h3>
                <ul>
                    <li><a href="#">Help & Support</a></li>
                    <li><a href="#">Privacy Policy</a></li>
                    <li><a href="#">About Us</a></li>
                    <li><a href="#">Contact</a></li>
                </ul>
            </div>

            <div class="card">
                <h2>Join Our Club</h2>
                <p> Lorem ipsum dolor sit amet consectetur adipisicing elit. Modi, nesciunt!</p>
                <a href="#" class="btn sc-btn">Join Now</a>
            </div>

            <div class="footer">
                <p>Copyright &copy; 2019, All Rights Reserved</p>
            </div>
        </div>
    </footer>
</body>

</html>

mailproject1/paipeline/templates/index.html
<!DOCTYPE html>
<html lang="en">
    {% load static %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>spam detector</title>
    <link href="https://fonts.googleapis.com/css?family=Lato|Staatliches" rel="stylesheet">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css"
        integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" crossorigin="anonymous">
    <link rel="shortcut icon" type="image/x-icon" href="favicon.ico">
    
    <link rel="stylesheet" href="{% static 'Css/style.css' %}">
    <link rel="stylesheet" href="{% static 'Css/mobile.css' %}">
</head>

<body>
    <nav class="navBar">
        <div class="container">
            <img src="Images/logo.png" alt="spam detector">
            <div class="social">
                <a href="http://facebook.com" target="_blank"><i class="fab fa-facebook fa-2x"></i></a>
                <a href="http://twitter.com" target="_blank"><i class="fab fa-twitter fa-2x"></i></a>
                <a href="http://instagram.com" target="_blank"><i class="fab fa-instagram fa-2x"></i></a>
                <a href="http://youtube.com" target="_blank"><i class="fab fa-youtube fa-2x"></i></a>
            </div>
            <div class="navBtns">
                <a href="index.html" class="btn current">Home</a>
                <a href="about.html" class="btn nCurrent">About</a>
            </div>
        </div>
    </nav>
    <header class="showcase">
        <div class="container">
            <div id="showcaseGrid">
               <form action="{% url 'paipeline:index' %}" method = "POST">
                {% csrf_token %}
                <h1>Enter the mail to know if it's spam or not</h1>
                <textarea name="mail" id="mail" cols="120" rows="13" placeholder="I'm excited to figure out!">{{mail}}</textarea>
                <input class="pr-btn btn" type="submit" value="Let's See!">
                <label {% if result == 'spam' %}
                style="background-color: red;"
                {% endif %}  >{{ result }}</label>
               </form>
            </div>
        </div>
    </header>


</body>

</html>